parent_pool_size: 20
offspring_pool_size: 40
max_generations: 50
max_indiv_age: 0
num_elites: 0

evolution:
  strategy: "mu_plus_lambda"

representation:
  type: "vector"
  initializer: random_initializer
  dim: 16  # Match with paranet.n_parameters
  bounds: [-1.0, 1.0]

mutation:
  strategy: "constant"
  strength: 0.1
  probability: 1.0

