parent_pool_size: 20
offspring_pool_size: 60
max_generations: 150
max_indiv_age: 0
num_elites: 0

evolution:
  strategy: mu_plus_lambda

modules:
  nnet:
    type: vector
    initializer: random_initializer
    dim: 16
    bounds: [-1.0, 1.0]
    mutation:
      strategy: constant
      strength: 0.1
      probability: 1.0
