# Sample configuration for 02_netvector_modulated_output.py

parent_pool_size: 20
offspring_pool_size: 40
max_generations: 50
num_elites: 1
max_indiv_age: 0

evolution:
  strategy: mu_plus_lambda

modules:
  controller:
    type: vector
    dim: 1
    initializer: normal_vector
    bounds: [-2.0, 2.0]
    mutation:
      strategy: constant
      strength: 0.1
      probability: 1.0
    crossover:
      strategy: none

  nnet:
    type: vector
    structure: net
    dim: [1, 16, 16, 1]
    initializer: normal_net
    mutation:
      strategy: constant
      strength: 0.05
      probability: 1.0
    crossover:
      strategy: none
