# Sample configuration for 01_evonet_sine_approximation.py

parent_pool_size: 20
offspring_pool_size: 140
max_generations: 25
max_indiv_age: 0
num_elites: 2

evolution:
  strategy: mu_comma_lambda

modules:
  nnet:
    type: evonet
    dim: [1, 6, 6, 1]
    activation: ["linear", "tanh", "tanh", "tanh"]
    initializer: normal_evonet
    bounds: [-1.0, 1.0]
    mutation:
      strategy: exponential_decay
      min_strength: 0.01
      max_strength: 0.1
      min_probability: 1.0
      max_probability: 1.0
