parent_pool_size: 20
offspring_pool_size: 40
max_generations: 200
max_indiv_age: 0
num_elites: 0

stopping:
  target_fitness: 0.001

evolution:
  strategy: mu_plus_lambda

modules:
  brain:
    type: evonet
    dim: [2, 0, 0, 1]
    activation: [linear, tanh, tanh, sigmoid]
    initializer: normal_evonet
    weight_bounds: [-5.0, 5.0]
    bias_bounds: [-1.0, 1.0]

    mutation:
      strategy: constant
      strength: 0.1
      probability: 0.9

      biases:
        strategy: constant
        strength: 0.05
        probability: 0.8

      structural:
        add_neuron: 0.03
        recurrent: "none"  # Optionen: none | direct | local | all
        remove_neuron: 0.01
        add_connection: 0.05
        remove_connection: 0.01
        split_connection: 0.02

        max_nodes: 3
        max_edges: 20
